### ISSUE TITLE
Adoption Form

### ISSUE THREAD

**Issue by JacobK233811** [gideontong/Destiny#3]
Using HTML forms to collect all the necessary information to execute an adoption.

**Comment by JacobK233811** [comment]
Going to follow a YouTube tutorial to complete this, and then create a similar form to collect information on age and sex to filter the random search and display (ie. dogs for male, cats for female).

So far it seems like it'll involve extending Component, defining some methods to handle events, and writing the HTML for the form. If it's alright with you @ainneo, I'll integrate some Reactstrap (React + Bootstrap) which can be installed like 
`$ yarn add reactstrap react react-dom bootstrap`
with Yarn or 
`$ npm install --save reactstrap react react-dom`
`$ npm install bootstrap --save`
`$ npm install --save reactstrap react react-dom`
with NPM.

Will keep you posted as I progress.

**Comment by ainneo** [comment]
Awesome! Thanks!

**Comment by ainneo** [comment]
I created a contact form and added it to the front end.
